name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Placeholder for building our docker image (and maybe deploying to demo site?)
  build:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: production

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and configure app
      run: |
        npm ci
        cp .env.example .env
