name: Lint and Tests


on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: test

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and configure app
      run: |
        npm ci
        cp .env.example .env
    - run: npm run lint

  test:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: test

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and configure app
      run: |
        npm ci
        cp .env.example .env
    - run: npm test
